.PHONY: clean All

All:
	@echo "----------Building project:[ MovieTracker - Debug ]----------"
	@cd "MovieTracker" && "$(MAKE)" -f  "MovieTracker.mk"
clean:
	@echo "----------Cleaning project:[ MovieTracker - Debug ]----------"
	@cd "MovieTracker" && "$(MAKE)" -f  "MovieTracker.mk" clean
